name: Deploy WordPress Content

on:
  push:
    branches:
      - main   # change if using another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      - name: using floder owner
        run: |
          ssh -p ${{ secrets.SERVER_PORT }} \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
          "sudo chown -R ${{ secrets.SERVER_USER }} /var/www/html/wp-content"
      - name: Deploy wp-content to server
        run: |
          rsync -avz --delete \
          -e "ssh -p ${{ secrets.SERVER_PORT }}" \
          ./wp-content/ \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/html/wp-content/
      - name: Changing the floder ownership to www-data
        run: |
          ssh -p ${{ secrets.SERVER_PORT }} \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
          "sudo chown -R root:root /var/www/html/wp-content"
      
